### ISSUE TITLE
Null Response from indexer endpoint for existing tx's 

### ISSUE THREAD

**Issue by ZacharyWeiner** [shruggr/1sat-indexer#1]
I have a series of Insicription transactions that I can verify on chain, but when I query them from the 
https://ordinals.gorillapool.io/api/inscriptions/<txid> endpoint I get a null value back. 

Here are some examples. 
db1299e879ee4bee6b432ee51c303295afa3d27d446714261a78931290c7d9f0_0
69169bbb802b1982fa879b2be0b05817916bf458fcdd04ff22387de60a61cb83_0

**Comment by shruggr** [comment]
Re-indexing has caught these
