### ISSUE TITLE
issue from scrypt

### ISSUE THREAD

**Issue by zhfnjust** [shruggr/1sat-indexer#13]
- [ ] old api return some token, but v3 return nothing: 
    https://ordinals.gorillapool.io/api/utxos/address/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/LUNC?fromHeight=0&fromIdx=0&limit=100
    https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/LUNC

- [ ]  a invalid transfer appear in activity:

    ![image](https://github.com/shruggr/1sat-indexer/assets/995909/b884c3ef-a68a-43cf-b966-ee124c8429ba)
    
    https://whatsonchain.com/tx/2761e8c191e151827bb08826b75605b605c290e50a9cda8f8c4710e92452a5e4
- [ ]  always keep this:
    
    ![image](https://github.com/shruggr/1sat-indexer/assets/995909/776004c8-4970-44c2-9723-99a215ac92f5)

- [ ] deploy and mint and transfer in one block,token showed, but api return nothing. both old and `v3`

    deploytx: [563f4658d1894739d2abc561d7d1048037e702bb2c73b20d6c885aa8375b1ebc](https://whatsonchain.com/tx/563f4658d1894739d2abc561d7d1048037e702bb2c73b20d6c885aa8375b1ebc)
    mint tx: [42e699dfc33f7fc1e9d1e37370b45fb9ac44ceb71d393b7c41f9f571166cca29](https://whatsonchain.com/tx/42e699dfc33f7fc1e9d1e37370b45fb9ac44ceb71d393b7c41f9f571166cca29)
   transfer tx: [4e0497463ad2ef2fb3bba49f686031633fbc92ac69791cc624eae786e5b9bc9d](https://whatsonchain.com/tx/4e0497463ad2ef2fb3bba49f686031633fbc92ac69791cc624eae786e5b9bc9d)

- [ ]  api return nothing after token [transfer](https://whatsonchain.com/tx/3309c5656e08db540d4d866dd35cdb148376ce3ec5767e42bc996682f44ba7d9) but token showed on https://1satordinals.com/. both old api and `v3` api have same issue.
   
   
   ![image](https://github.com/shruggr/1sat-indexer/assets/995909/b16365fa-0222-4c06-97fe-812a9ac1fd6e)

   https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/MLGB
   https://ordinals.gorillapool.io/api/utxos/address/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/MLGB?fromHeight=0&fromIdx=0&limit=100

v2:

- [x]  token deploy in a p2pkh, but api returns nothing 
    deploy tx: https://whatsonchain.com/tx/8e42e29e7a39ec11eed7000834b6c062945be458368b8577173ec0a1d41d4804
    api: https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/id/8e42e29e7a39ec11eed7000834b6c062945be458368b8577173ec0a1d41d4804_0

**Comment by zhfnjust** [comment]
v2:

1. token deploy in a p2pkh, but api returns nothing 
    deploy tx: https://whatsonchain.com/tx/8e42e29e7a39ec11eed7000834b6c062945be458368b8577173ec0a1d41d4804
    api: https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/id/8e42e29e7a39ec11eed7000834b6c062945be458368b8577173ec0a1d41d4804_0

**Comment by shruggr** [comment]
@zhfnjust the web-server was missing the `deploy+mint` utxo on these. This should be resolved now.

**Comment by zhfnjust** [comment]
> @zhfnjust the web-server was missing the `deploy+mint` utxo on these. This should be resolved now.

ok, it fixed. but how about above issue?

**Comment by zhfnjust** [comment]
an other different results:

https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/VIVO return 2 token utxo

https://ordinals.gorillapool.io/api/utxos/address/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/VIVO?fromHeight=0&fromIdx=0&limit=100  returns 4 token utxo.

**Comment by zhfnjust** [comment]
# Summary of API testing

# NFT: 

- [mint](https://whatsonchain.com/tx/23b05a5fdaee7fd243622c5c8e64aba0a53e6e5b0e0c3e3f04d85bdfd7219b67) in a p2pkh, then [transfer](https://whatsonchain.com/tx/6fb1b5eca5de982bf4f452861b28d5f67cef464aa43a6750d8d76316b7157402)  to a p2pkh
	- [x] old [api](https://ordinals.gorillapool.io/api/inscriptions/origin/23b05a5fdaee7fd243622c5c8e64aba0a53e6e5b0e0c3e3f04d85bdfd7219b67_0/latest) returns correctly
	- [x] `v3` [api](https://v3.ordinals.gorillapool.io/api/inscriptions/23b05a5fdaee7fd243622c5c8e64aba0a53e6e5b0e0c3e3f04d85bdfd7219b67_0/latest?script=false) returns correctly
- [mint](https://whatsonchain.com/tx/6d8269bfcc7e703aa3178f5df11c1ffe7ed02e1e3b81c5c3fe46250775f32e58) in contract, then [transfer](https://whatsonchain.com/tx/74230eec3666f3b4c67dcf740b586229d9bbee0edac02194310804d4de67eb56) to a p2pkh
	- [x] old [api](https://ordinals.gorillapool.io/api/inscriptions/origin/6d8269bfcc7e703aa3178f5df11c1ffe7ed02e1e3b81c5c3fe46250775f32e58_0/latest) returns correctly
	- [x] `v3` [api](https://v3.ordinals.gorillapool.io/api/inscriptions/6d8269bfcc7e703aa3178f5df11c1ffe7ed02e1e3b81c5c3fe46250775f32e58_0/latest?script=false) returns correctly

# FT V1

deploy : 

- [deploy](https://whatsonchain.com/tx/edb4d96881a5e63170fbb85bad5f7f6fe9a6ac006cb38fbf13d2adb9b0e2feec) in a p2pkh
	- [x] old [api](https://ordinals.gorillapool.io/api/bsv20/KKK1) returns correctly 
	- [x] `v3` [api](https://v3.ordinals.gorillapool.io/api/bsv20/tick/KKK1) returns correctly after `7` blocks confirmed


mint and transfer : 

- [mint](https://whatsonchain.com/tx/dc4034e518f50f9fe5f5e56449417f97a7491604d7b18b5c0417c68474b5633d) in a p2pkh, then [transfer](https://whatsonchain.com/tx/3691c3ead966520410f85e297041ed686d4ad119b3c14383b979bdae0292968e) to p2pkh
	- [ ] **old api returns nothing**
	- [x] `v3` api returns correctly after `7` blocks confirmed
- [mint](https://whatsonchain.com/tx/28d249bc839a44585891148292635753e620fd68e71cd2939a2dd5188ca2c9ae) in a contract, then [transfer](https://whatsonchain.com/tx/79c1ae956b38badc0799bcd96eba3ad86652a3f148c15e0309e617ee9ddc5ddd) to a p2pkh
	- [ ] **old [api](https://ordinals.gorillapool.io/api/utxos/address/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/KKK1?fromHeight=0&fromIdx=0&limit=100) returns nothing**
	- [x] `v3` [api](https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/KKK1) returns correctly after `7` blocks confirmed

# FT V2

- [mint](https://whatsonchain.com/tx/1ab32db1ab484378008e59b411808878ae6bec64392c31cef6124143995afcc4) in a p2pkh, then [transfer](https://whatsonchain.com/tx/708ae8529e1a30f74b97b04cf77732eed7289fdac3640b76dbd07a02dcd3674c) to p2pkh
	- [x] `v3` [api](https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/id/1ab32db1ab484378008e59b411808878ae6bec64392c31cef6124143995afcc4_0) returns correctly after `1` blocks confirmed
- [mint](https://whatsonchain.com/tx/945a0036545b46ead4a972573b1c8bd34728fd9e21771c1c56f87cf4dadcb144) in contract, then [transfer](https://whatsonchain.com/tx/13835529a822720f36aef1ed3d5892f28910bb687d74fe1ba95b903c2580fc47) to a p2pkh
	- [x] `v3` [api](https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/id/945a0036545b46ead4a972573b1c8bd34728fd9e21771c1c56f87cf4dadcb144_0) returns correctly after `1` blocks confirmed


-----------------------------------------


> some case **old api returns nothing** may returns correctly after manay blocks confirmed.

**Comment by xhliu** [comment]
- [ ]  old api return some token, but v3 return nothing:
https://ordinals.gorillapool.io/api/utxos/address/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/LUNC?fromHeight=0&fromIdx=0&limit=100
https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/LUNC

**Comment by freedomhero** [comment]
Another concern is about the indexing speed. Even for the testnet blocks, indexing appears to be slow.

For example, the following log fragment focuses on the process of block #1147909, which has 29 transactions. It appears that about 8 seconds were spent on processing from the start of the job 'crawling,' which began around '2023/10/09 03:54:19,' to the end of the job 'Validating BSV20 mint,' which ended around '2023/10/09 03:54:27'.

```
2023/10/09 03:54:19 Done validating BSV20 1147907
txcount 4
Crawling Forward 1147909 0000000000001b49880157efbe5141a6d7da9a732c45624e4340483dd63e5191
Completed: 1147902 txns: 4
Validating bsv20 for height 1147908
2023/10/09 03:54:20 Validating BSV20 1147908
Processing inscription ids for height 1147902
2023/10/09 03:54:20 Validating BSV20 mint 1147908
Validating BSV20 mint 1147902
2023/10/09 03:54:20 Validating BSV20 transfers 1147908
Processing Block 1147909 0000000000001b49880157efbe5141a6d7da9a732c45624e4340483dd63e5191
txcount 29
2023/10/09 03:54:20 Done validating BSV20 1147908
Completed: 1147903 txns: 29
Validating bsv20 for height 1147909
2023/10/09 03:54:23 Validating BSV20 1147909
Processing inscription ids for height 1147903
Crawling Forward 1147910 00000000000023043dbcb4541dce2b9c7adade82a44757582dc2de5cb0b251f3
2023/10/09 03:54:23 Validating BSV20 mint 1147909
Validating BSV20 mint 1147903
2023/10/09 03:54:23 Validating BSV20 transfers 1147909
2023/10/09 03:54:23 Done validating BSV20 1147909
Processing Block 1147910 00000000000023043dbcb4541dce2b9c7adade82a44757582dc2de5cb0b251f3
txcount 12
Completed: 1147904 txns: 12
Validating bsv20 for height 1147910
Processing inscription ids for height 1147904
2023/10/09 03:54:24 Validating BSV20 1147910
Crawling Forward 1147911 000000000000093071c31bcf98faef2117764038a0ed9b14e6886c8d49318897
2023/10/09 03:54:24 Validating BSV20 mint 1147910
Validating BSV20 mint 1147904
2023/10/09 03:54:24 Validating BSV20 transfers 1147910
2023/10/09 03:54:24 Done validating BSV20 1147910
Processing Block 1147911 000000000000093071c31bcf98faef2117764038a0ed9b14e6886c8d49318897
txcount 10
Crawling Forward 1147912 0000000000001ddfb2211dcaf2f3d305b4a007e6c9356bab47bb52797317c39b
Completed: 1147905 txns: 10
Validating bsv20 for height 1147911
2023/10/09 03:54:24 Validating BSV20 1147911
Processing inscription ids for height 1147905
2023/10/09 03:54:25 Validating BSV20 mint 1147911
Validating BSV20 mint 1147905
2023/10/09 03:54:25 Validating BSV20 transfers 1147911
Processing Block 1147912 0000000000001ddfb2211dcaf2f3d305b4a007e6c9356bab47bb52797317c39b
2023/10/09 03:54:25 Done validating BSV20 1147911
txcount 1
Crawling Forward 1147913 0000000000002ec97f8387e47cfb6c3e5abbb6aecda3516039c3d682ddb975fe
Completed: 1147906 txns: 1
Validating bsv20 for height 1147912
2023/10/09 03:54:25 Validating BSV20 1147912
Processing inscription ids for height 1147906
2023/10/09 03:54:25 Validating BSV20 mint 1147912
Validating BSV20 mint 1147906
2023/10/09 03:54:25 Validating BSV20 transfers 1147912
2023/10/09 03:54:25 Done validating BSV20 1147912
Processing Block 1147913 0000000000002ec97f8387e47cfb6c3e5abbb6aecda3516039c3d682ddb975fe
txcount 13
Completed: 1147907 txns: 13
Validating bsv20 for height 1147913
2023/10/09 03:54:26 Validating BSV20 1147913
Processing inscription ids for height 1147907
Crawling Forward 1147914 0000000000001a0f7591fe9deed0ff52ef830242d28b4d53c2a5f09aeed62cf6
2023/10/09 03:54:26 Validating BSV20 mint 1147913
Validating BSV20 mint 1147907
2023/10/09 03:54:26 Validating BSV20 transfers 1147913
2023/10/09 03:54:26 Done validating BSV20 1147913
Processing Block 1147914 0000000000001a0f7591fe9deed0ff52ef830242d28b4d53c2a5f09aeed62cf6
txcount 13
Crawling Forward 1147915 000000000000350cfb16336383f3d6a364574b77ad0bc8e5bcb3e9610dd234de
Completed: 1147908 txns: 13
Processing inscription ids for height 1147908
Validating bsv20 for height 1147914
2023/10/09 03:54:27 Validating BSV20 1147914
2023/10/09 03:54:27 Validating BSV20 mint 1147914
Validating BSV20 mint 1147908
2023/10/09 03:54:27 Validating BSV20 transfers 1147914
2023/10/09 03:54:27 Done validating BSV20 1147914
Processing Block 1147915 000000000000350cfb16336383f3d6a364574b77ad0bc8e5bcb3e9610dd234de
txcount 1
Crawling Forward 1147916 000000000000254e089ec5669e9cac55134c2dbb83475976c0f66ee0da52e9fc
Completed: 1147909 txns: 1
Validating bsv20 for height 1147915
2023/10/09 03:54:27 Validating BSV20 1147915
Processing inscription ids for height 1147909
2023/10/09 03:54:27 Validating BSV20 mint 1147915
Validating BSV20 mint 1147909
2023/10/09 03:54:27 Validating BSV20 transfers 1147915
```
Here are some more samples:

| txs | secs 
| ---- | ---- 
| 255 | 62
| 387 | 71
| 2275 | 900
| 2533 | 1110
| 2547 | 1455
| 2690 | 1260


Is there anything I can do to speed up the process?

By the way, the testnet node is running on the same host as the indexer, so the RPCs should have low network latency. Also, the host's CPU and memory usage are very low, so I do not think that is a bottleneck for indexing.

**Comment by shruggr** [comment]
How big of a box were you indexing on? How many cores/RAM?

**Comment by freedomhero** [comment]
2 cores / 4GB RAM. The CPU usage is less than 5%, and the memory usage is less than 40%.
