### ISSUE TITLE
indexer does not recognize inscription if placed BEFORE p2pkh

### ISSUE THREAD

**Issue by xhliu** [shruggr/1sat-indexer#14]
In sCrypt, we place inscription before locking script logic in stateful & stateless contracts, for consistency.

**Comment by shruggr** [comment]
Please provide an example txid

**Comment by xhliu** [comment]
@zhfnjust

**Comment by xhliu** [comment]
> Please provide an example txid

https://whatsonchain.com/tx/c4a472d166d9e5b8586be28846cb9329d8c12b4421e5050204556ab125c66d9b

**Comment by zhfnjust** [comment]
a example [tx](https://whatsonchain.com/tx/0333d5c00a58cb420ecb8185692c66723311d9f212dee7ef6409dceddcaabcb3) with  inscription placed BEFORE p2pkh.

now  recognize  with `v3` apis: 

https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/VIVO

but still not recognize by old api:

https://ordinals.gorillapool.io/api/utxos/address/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/tick/VIVO?fromHeight=0&fromIdx=0&limit=100

@xhliu @shruggr
