### ISSUE TITLE
testnet api not work

### ISSUE THREAD

**Issue by zhfnjust** [shruggr/1sat-indexer#16]
with testnet address: https://testnet.ordinals.gorillapool.io/api/bsv20/mqe2d39Yb8UdA6mowX9iWMdcRFYXrNQMje/tick/VIVO

![image](https://github.com/shruggr/1sat-indexer/assets/995909/0b61ac3c-94d9-4ffe-9c6e-2ce215309a6e)

**Comment by shruggr** [comment]
Site has been updated to use testnet addresses
