### ISSUE TITLE
bsv20 v1, v2 not working - testnet

### ISSUE THREAD

**Issue by zhfnjust** [shruggr/1sat-indexer#18]
deploy + mint: 

https://test.whatsonchain.com/tx/fa2e480d180203726dcbe4aa2231544ee64d9c888b3a426e8d0c7f244a18d944

transfer:

https://test.whatsonchain.com/tx/91b019e5cc83faf6ae704abf4a08abd3df31881ae7cd31b95d9e73d20c10a055

**THIS API returns nothing**

https://testnet.ordinals.gorillapool.io/api/bsv20/mqe2d39Yb8UdA6mowX9iWMdcRFYXrNQMje/id/fa2e480d180203726dcbe4aa2231544ee64d9c888b3a426e8d0c7f244a18d944_0

**Comment by shruggr** [comment]
It appears that the status value was never set, to the transfer was never validated. Researching now to see how that could possibly happen

**Comment by zhfnjust** [comment]
`v1` not working too.

mint : https://test.whatsonchain.com/tx/7ca630ae5f974ba6a4cb1ad34401e3c0e7208029d0d0f52a187f2f7453ea4ff9
transfer: https://test.whatsonchain.com/tx/95048e7967bec7fb996c0c5fc347529d0fa0651e183961defb4aba16c6edb5ff

api returns nothing: https://testnet.ordinals.gorillapool.io/api/bsv20/mqe2d39Yb8UdA6mowX9iWMdcRFYXrNQMje/tick/VIVO

**Comment by shruggr** [comment]
Please try again. Testnet did not have the newest fixes from prod applied. I have applied the updates and reindexed from block 1576000

**Comment by zhfnjust** [comment]
still returns nothing:

https://testnet.ordinals.gorillapool.io/api/bsv20/mqe2d39Yb8UdA6mowX9iWMdcRFYXrNQMje/id/1d1d14a96e21ca65b1a9d2c886347f8cdd64a1fe846c63de44d033f996e890da_0


already comfirmed in block: 

![image](https://github.com/shruggr/1sat-indexer/assets/995909/1b52f5dd-e21e-43e1-b84f-155233af2a2d)

@shruggr

**Comment by zhfnjust** [comment]
same as `v1` .

mint: https://test.whatsonchain.com/tx/1b20cca6e3fbff253f7f798c6cdbbe39e52c51036e82cbbc38c191e1215e19b7
transfer: https://test.whatsonchain.com/tx/bd2727e8d9980ad93dc3fc127ae767cd7156f3eb1c0f2faaf59d1042d041969b

**Comment by zhfnjust** [comment]
@shruggr any update?

**Comment by shruggr** [comment]
Sorry. I've been traveling the last 2 days. I'm back home and working on this today

**Comment by shruggr** [comment]
I just did a re-index with all of the newest rules applied, and the data showed up as expected. Please continue testing and let me know if you see continued issues.

**Comment by zhfnjust** [comment]
now work fine
