### ISSUE TITLE
Precision lost

### ISSUE THREAD

**Issue by zhfnjust** [shruggr/1sat-indexer#20]
![image](https://github.com/shruggr/1sat-indexer/assets/995909/29cf1daa-0958-49d1-b25c-dbf1dd6b284e)

https://v3.ordinals.gorillapool.io/api/bsv20/1sM8JmXi8WBwtDU28XsBJdR5i428E1dYA/balance

**Comment by shruggr** [comment]
Fixed. Be aware that confirmed and pending values are now strings.
